# Custom Language File for Launcher Customizer

[ejs.app]
title = "Japsik Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Japsik-Server/JapsikLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.japsik.com"

[ejs.settings]
sourceGithubLink = "https://github.com/Japsik-Server/JapsikLauncher"
supportLink = "https://discord.japsik.com"

[ejs.welcome]
welcomeHeader = "잡식 런처에 오신 걸 환영합니다!"
welcomeDescription = "여러 서버에서 즐겁게 마인크래프트를 플레이 해보세요!"
welcomeDescCTA = "단 몇번의 클릭만으로 서버에 접속하실 수 있어요."
