# Custom Language File for Launcher Customizer

[ejs.app]
title = "Japsik Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/thecats1105/Japsik"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/japsik"

[ejs.settings]
sourceGithubLink = "https://github.com/thecats1105/Japsik"
supportLink = "https://github.com/thecats1105/Japsik/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO JAPSIK"
welcomeDescription = "Our Making City in Minecraft"
welcomeDescCTA = "You are just a few clicks away from Japsik."
