name: Release Build

on: 
  push:
      branches:
        - main

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    permissions:
      contents: write


    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          npm ci
          echo -e "\033[32m"Dependencies Installation Completed
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run dist:win
          echo -e "\033[32m"Build Completed
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/**
          if-no-files-found: warn
          retention-days: 30